// Cross-language conformance against protocol/testvectors (generated by the
// Go reference implementation: go test ./pkg/e2e -run TestVectors -update).
import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:family_messenger_e2e/crypto/account.dart';
import 'package:family_messenger_e2e/crypto/bytes.dart';
import 'package:family_messenger_e2e/crypto/envelope.dart';
import 'package:family_messenger_e2e/crypto/files.dart';
import 'package:family_messenger_e2e/crypto/fingerprint.dart';
import 'package:family_messenger_e2e/crypto/ids.dart';
import 'package:family_messenger_e2e/crypto/primitives.dart';
import 'package:family_messenger_e2e/crypto/seal.dart';

Map<String, dynamic> load(String name) {
  for (final c in ['../protocol/testvectors/$name', 'protocol/testvectors/$name']) {
    final f = File(c);
    if (f.existsSync()) return jsonDecode(f.readAsStringSync()) as Map<String, dynamic>;
  }
  throw StateError('vectors not found: $name');
}

final Uint8List Function(String) h = hexToBytes;

void main() {
  group('kdf vectors', () {
    final v = load('kdf.json');
    final params = KdfParams.fromJson(v['params'] as Map<String, dynamic>);
    final cases = v['cases'] as List<dynamic>;
    for (var i = 0; i < cases.length; i++) {
      final c = cases[i] as Map<String, dynamic>;
      test('case $i', () async {
        final d = await deriveKeys(c['password'] as String, h(c['salt'] as String), params);
        expect(bytesToHex(d.authKey), c['auth_key']);
        expect(bytesToHex(d.encKey), c['enc_key']);
        expect(bytesToHex(await sha256(d.authKey)), c['auth_hash']);
      }, timeout: const Timeout(Duration(minutes: 5)));
    }
  });

  group('keys vectors', () {
    final cases = load('keys.json')['cases'] as List<dynamic>;
    for (var i = 0; i < cases.length; i++) {
      final c = cases[i] as Map<String, dynamic>;
      test('case $i', () async {
        final keys = await keysFromSecrets(h(c['sign_seed'] as String), h(c['enc_priv'] as String));
        expect(bytesToHex(keys.signPub), c['sign_pub']);
        expect(bytesToHex(keys.encPub), c['enc_pub']);
        expect(await fingerprint(keys.signPub, keys.encPub), c['fingerprint']);
        final msg = h(c['message'] as String);
        expect(bytesToHex(await sign(keys.signSeed, msg)), c['signature']);
        expect(await verify(keys.signPub, msg, h(c['signature'] as String)), isTrue);
        expect(bytesToHex(await sealKeyBundle(h(c['bundle_enc_key'] as String), h(c['bundle_nonce'] as String), keys)), c['bundle']);
        final opened = await openKeyBundle(h(c['bundle_enc_key'] as String), h(c['bundle'] as String), keys.signPub, keys.encPub);
        expect(bytesToHex(opened.signSeed), c['sign_seed']);
        expect(bytesToHex(opened.encPriv), c['enc_priv']);
      });
    }
  });

  group('seal vectors', () {
    final cases = load('seal.json')['cases'] as List<dynamic>;
    for (var i = 0; i < cases.length; i++) {
      final c = cases[i] as Map<String, dynamic>;
      test('case $i', () async {
        final box = await sealWith(
          h(c['ephemeral_priv'] as String),
          h(c['recipient_enc_pub'] as String),
          h(c['conv_id'] as String),
          h(c['recipient_account'] as String),
          h(c['key'] as String),
        );
        expect(bytesToHex(box), c['box']);
        final key = await open(h(c['recipient_enc_priv'] as String), h(c['conv_id'] as String), h(c['recipient_account'] as String), h(c['box'] as String));
        expect(bytesToHex(key), c['key']);
        await expectLater(
          open(h(c['recipient_enc_priv'] as String), h(c['recipient_account'] as String), h(c['conv_id'] as String), h(c['box'] as String)),
          throwsA(anything),
        );
      });
    }
  });

  group('envelope vectors', () {
    final cases = load('envelope.json')['cases'] as List<dynamic>;
    for (final raw in cases) {
      final c = raw as Map<String, dynamic>;
      test(c['name'] as String, () async {
        final recipientsJson = (c['recipients'] as List<dynamic>).cast<Map<String, dynamic>>();
        final hdr = Header(
          flags: c['flags'] as int,
          convId: bytesToUuid(h(c['conv_id'] as String)),
          senderAccount: bytesToUuid(h(c['sender_account'] as String)),
          senderDevice: bytesToUuid(h(c['sender_device'] as String)),
          clientMsgId: bytesToUuid(h(c['client_msg_id'] as String)),
          timestampMs: c['ts_ms'] as int,
        );
        final recipients = [
          for (final r in recipientsJson) Recipient(account: bytesToUuid(h(r['account'] as String)), encPub: h(r['enc_pub'] as String)),
        ];
        final out = await encryptWith(
          h(c['sender_sign_seed'] as String),
          hdr,
          recipients,
          h(c['plaintext'] as String),
          Randomness(
            key: h(c['message_key'] as String),
            nonce: h(c['nonce'] as String),
            ephemeral: [for (final r in recipientsJson) h(r['ephemeral_priv'] as String)],
          ),
        );
        expect(bytesToHex(out.env), c['envelope']);
        expect(bytesToHex(out.sig), c['signature']);
        expect(await verifyEnvelope(h(c['sender_sign_pub'] as String), h(c['envelope'] as String), h(c['signature'] as String)), isTrue);
        final parsed = parse(h(c['envelope'] as String));
        expect(parsed.header.flags, c['flags']);
        expect(parsed.header.convId, hdr.convId);
        expect(parsed.header.senderAccount, hdr.senderAccount);
        expect(parsed.header.clientMsgId, hdr.clientMsgId);
        expect(parsed.header.timestampMs, c['ts_ms']);
        for (final r in recipientsJson) {
          final pt = await decrypt(parsed, bytesToUuid(h(r['account'] as String)), h(r['enc_priv'] as String));
          expect(bytesToHex(pt), c['plaintext']);
        }
      });
    }
  });

  test('round trip with random keys', () async {
    final alice = await generateKeys();
    final bob = await generateKeys();
    final aliceId = newUuid();
    final bobId = newUuid();
    final hdr = Header(
      flags: flagEphemeral,
      convId: newUuid(),
      senderAccount: aliceId,
      senderDevice: newUuid(),
      clientMsgId: newUuid(),
      timestampMs: DateTime.now().millisecondsSinceEpoch,
    );
    final pt = utf8Encode('{"t":"text","body":"привет"}');
    final out = await encrypt(alice.signSeed, hdr, [Recipient(account: aliceId, encPub: alice.encPub), Recipient(account: bobId, encPub: bob.encPub)], pt);
    expect(await verifyEnvelope(alice.signPub, out.env, out.sig), isTrue);
    expect(await verifyEnvelope(bob.signPub, out.env, out.sig), isFalse);
    final parsed = parse(out.env);
    expect(bytesToHex(await decrypt(parsed, bobId, bob.encPriv)), bytesToHex(pt));
    expect(bytesToHex(await decrypt(parsed, aliceId, alice.encPriv)), bytesToHex(pt));
    await expectLater(decrypt(parsed, bobId, alice.encPriv), throwsA(anything));
    final tampered = Uint8List.fromList(out.env);
    tampered[tampered.length - 1] ^= 1;
    expect(await verifyEnvelope(alice.signPub, tampered, out.sig), isFalse);
  });

  test('attachment encryption round trip', () async {
    final data = randomBytes(1000);
    final enc = await encryptFile(data);
    expect(enc.ciphertext.length, data.length + tagSize);
    expect(bytesToHex(await decryptFile(enc.key, enc.nonce, enc.ciphertext)), bytesToHex(data));
    await expectLater(decryptFile(randomBytes(32), enc.nonce, enc.ciphertext), throwsA(anything));
  });

  // The proof a signed-in device gives instead of the old password
  // (PROTOCOL.md §3.2). The server rebuilds these exact bytes, so a client
  // that lays them out differently cannot change its password at all.
  group('password change vectors', () {
    final cases = load('pwchange.json')['cases'] as List<dynamic>;
    for (var i = 0; i < cases.length; i++) {
      final c = cases[i] as Map<String, dynamic>;
      test('case $i', () async {
        final signOutOthers = c['sign_out_others'] == true;
        final msg = passwordChangeMessage(
          h(c['challenge'] as String),
          h(c['account_id'] as String),
          h(c['device_id'] as String),
          h(c['new_salt'] as String),
          h(c['new_auth_key'] as String),
          h(c['new_key_bundle'] as String),
          signOutOthers: signOutOthers,
        );
        expect(bytesToHex(msg), c['message']);
        final sig = await signPasswordChange(
          h(c['sign_seed'] as String),
          h(c['challenge'] as String),
          h(c['account_id'] as String),
          h(c['device_id'] as String),
          h(c['new_salt'] as String),
          h(c['new_auth_key'] as String),
          h(c['new_key_bundle'] as String),
          signOutOthers: signOutOthers,
        );
        expect(bytesToHex(sig), c['signature']);
        expect(await verify(h(c['sign_pub'] as String), msg, sig), isTrue);
      });
    }
  });
}
